name: OOOReview UI smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Puppeteer
        run: npm install puppeteer --no-audit --no-fund
      - name: Run UI smoke test
        run: node tools/ooo_ui_smoke.js
        env:
          CI: true
